### ISSUE TITLE
Installation as user fails

### ISSUE THREAD

**Issue by thopiekar** [euclid3/euclid3#8]
I was trying to install solidpython, but I got an error during installation, which seems to belog to this project. For a reason it seems that your script does not try to install into the pip directory, but to a read-only location at `/usr/local/lib`.

Regards

(Ubuntu Yakkety, Python 3.5.x)

```
thopiekar@home:~$ pip3 install solidpython
Collecting solidpython
  Downloading solidpython-0.2.0.tar.gz (51kB)
    100% |████████████████████████████████| 61kB 1.9MB/s 
Collecting euclid3 (from solidpython)
  Downloading euclid3-0.01.tar.gz
Collecting PyPNG (from solidpython)
  Downloading pypng-0.0.18.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 1.6MB/s 
Collecting prettytable (from solidpython)
  Downloading prettytable-0.7.2.zip
Building wheels for collected packages: solidpython, euclid3, PyPNG, prettytable
  Running setup.py bdist_wheel for solidpython ... done
  Stored in directory: /home/thopiekar/.cache/pip/wheels/11/d6/4c/2c188e2b1e5dab82b832de1aca68b6056ff5ed6537e55e8d26
  Running setup.py bdist_wheel for euclid3 ... done
  Stored in directory: /home/thopiekar/.cache/pip/wheels/27/37/8a/ffaa4aa72d532748889dab0119b49a98a2d7e79b581e44b2f3
  Running setup.py bdist_wheel for PyPNG ... done
  Stored in directory: /home/thopiekar/.cache/pip/wheels/6d/f0/c9/6e31bc9ec080ed16c9b84b305c55716ea227026904af2d52f1
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /home/thopiekar/.cache/pip/wheels/b6/90/7b/1c22b89217d0eba6d5f406e562365ebee804f0d4595b2bdbcd
Successfully built solidpython euclid3 PyPNG prettytable
Installing collected packages: euclid3, PyPNG, prettytable, solidpython
Exception:
Traceback (most recent call last):
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python3.5/dist-packages/euclid3.py'                                                                  
thopiekar@home:~$ LANG=C pip3 install solidpython                                                                                                                    
Collecting solidpython                                                                                                                                               
Collecting euclid3 (from solidpython)                                                                                                                                
Collecting PyPNG (from solidpython)                                                                                                                                  
Collecting prettytable (from solidpython)                                                                                                                            
Installing collected packages: euclid3, PyPNG, prettytable, solidpython                                                                                              
Exception:                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                   
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main                                                                    
    status = self.run(options, args)                                                                                                                                 
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run                                                                
    prefix=options.prefix_path,                                                                                                                                      
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install                                                                 
    **kwargs                                                                                                                                                         
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install                                                             
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)                                                                                                 
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files                                                   
    isolated=self.isolated,                                                                                                                                          
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/thopiekar/.local/lib/python3.5/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/euclid3.py'
```

**Comment by ccanepa** [comment]
Are you sure this one is the euclid3 that failed to install ? The euclid3 in pypi is not **this** euclid3, and I suppose your  'pip3 install solidpython' would fetch from pypi.
Both are forks from Alex Holkner euclid , so probably with same functionality.

**Comment by thopiekar** [comment]
Oh, ok. So the module called euclid3 can also come from the euclid repository, right?

I thought since this package is called euclid3 then it comes from your repo, too.

**Comment by ccanepa** [comment]
> Oh, ok. So the module called euclid3 can also come from the euclid repository, right?

The module found at pypi can come from anywhere.

> I thought since this package is called euclid3 then it comes from your repo, too.

No problem but no, code is different.
Looking at the pypi page I see 
```
Changes: Update to Python 3 in 2014 by Michael Zimmermann (www.incunabulum.de)
```

so maybe you can contact that guy

**Comment by thopiekar** [comment]
Ok, thanks. Well, since the last update was in 2014 I don't think that the maintainer of the package actually gives any support.

However, this is not related to this repo, so I'll close it.
